import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Layout from '../components/Layout'
import { Breadcrumb, Button } from "antd";
import MainHeading from '../components/CampaginInsight/ChartResult/MainHeading';
import CampaignResult from '../components/CampaginInsight/ChartResult/CampaignResult';
import PhoneStatus from '../components/CampaginInsight/PhoneStatus/PhoneStatus';


const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>TBS - Campaign Insight Detail</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/assets/img/favicon-96x96.png" />
      </Head>

      <Layout>
        <MainHeading />
        <CampaignResult />
        <PhoneStatus />
      </Layout>
    </>
  )
}

export default Home
